# Generated by Django 5.1.7 on 2025-03-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_bio_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
