# Generated by Django 5.1.7 on 2025-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tutorprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
