# Generated by Django 5.1.7 on 2025-03-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_address_studentprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects_interested',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjects_taught',
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_completed', models.PositiveIntegerField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='users.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='users.tutorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects_interested',
            field=models.ManyToManyField(related_name='interested_students', to='users.subject'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='tutors', to='users.subject'),
        ),
    ]
