# Generated by Django 5.1.6 on 2025-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subject_remove_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year_completed',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
