# Generated by Django 5.1.6 on 2025-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_qualification_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
