# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tutoravailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='connected_tutors',
            field=models.ManyToManyField(blank=True, default='', related_name='connected_students', to='users.tutorprofile'),
        ),
    ]
