# Generated by Django 5.1.6 on 2025-03-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_session_end_time_alter_session_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
