# Generated by Django 5.1.6 on 2025-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_session_meeting_link_alter_session_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics/students/'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics/tutors/'),
        ),
    ]
