# Generated by Django 5.1.6 on 2025-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
