# Generated by Django 5.1.6 on 2025-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tutorprofile_address_tutorprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
