# Generated by Django 5.1.6 on 2026-02-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_studentprofile_latitude_studentprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/students/'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/tutors/'),
        ),
    ]
